# -*- coding: utf-8 -*-
"""Rate My Professor scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XcYs86cm-08o7irKpuPitGNza-2ZK1Ia
"""

pip install ratemyprofessors-client

from rmp_client import (
    RMPClient,
    ParsingError,
    HttpError,
    analyze_sentiment,
    normalize_comment,
    is_valid_comment,
    build_course_mapping,
    clean_course_label,
)

from rmp_client.models import (
    School,
    Professor,
    Rating,
    SchoolRating,
    ProfessorSearchResult,
    SchoolSearchResult,
    ProfessorRatingsPage,
    SchoolRatingsPage,
    CompareSchoolsResult,
)

"""##Extracting professor information"""

school_name = "University of Miami"

with RMPClient() as client:
  try:
    school = next((s for s in School.schools if s.name == school_name), None)
    professors = client.list_professors_for_school(school.id)
  except ParsingError:
    print("School not found")
  except HttpError as e:
    print(f"HTTP error: {e.status_code}")

print(school)

id = 1241
departments = ["Computer Science", "Business Technology",
"Innovation, Technology, and Design", "Engineering",
"Cinema & Interactive Media", "Information Science",
"Electronic Media"]

professors = []

for department in departments:
  professors.append([p for p in client.iter_professors_for_school(id) if p.department == department])

professors

import csv

with open("professors.csv", "w", newline="") as f:
    writer = csv.writer(f)
    for i in range(len(professors)):
      for p in professors[i]:
          writer.writerow([
              p.id, p.name, p.department,
              p.overall_rating, p.num_ratings, p.percent_take_again,
              p.level_of_difficulty
          ])

import csv
import re

with open("professors.csv") as f_in, open("professors_clean.csv", "w", newline="") as f_out:
  reader = csv.reader(f_in)
  writer = csv.writer(f_out)

  for row in reader:
    cleaned = [re.sub(r'^\([^,]+,\s*', '', field).rstrip(')') for field in row]
    writer.writerow(cleaned)

df = pd.read_csv("professors_clean.csv")
df.columns = ['ID', 'Name', 'Department','Overall Rating', 'Number of Ratings', 'Would Take Again Percent', 'Level of Difficulty']
df.to_csv('professors_clean.csv', index=False)

from google.colab import files
import pandas as pd

files.download("professors_clean.csv")

"""## Getting Reviews for Each Professor"""

reviews = {}

for i in range(len(professors)):
  for p in professors[i]:
    reviews[p.name] = []
    for rating in client.iter_professor_ratings(p.id):
      reviews[p.name].append(rating)

print(reviews)

headers = ['Date', 'Comment', 'Quality', 'Difficulty', 'Tags', 'Course',
           'For Credit', 'Attendance', 'Grade', 'Textbook', 'Thumbs Up', 'Thumbs Down']

for i  in range(len(professors)):
  for professor in professors[i]:
    file_name = professor.name + "_reviews.csv"

    with open(file_name, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        for rating in reviews[professor.name]:
            details = rating.details or {}
            writer.writerow([
                rating.date, rating.comment,
                rating.quality, rating.difficulty,
                ', '.join(rating.tags) if rating.tags else '',  # flatten list to string
                rating.course_raw,
                details.get('for_credit', ''),
                details.get('attendance', ''),
                details.get('grade', ''),
                details.get('textbook', ''),
                rating.thumbs_up,
                rating.thumbs_down
            ])

"""##Downloading professor reviews as zip file"""

import zipfile
import os

with zipfile.ZipFile("professor_reviews.zip", "w") as zf:
  for i in range(len(professors)):
    for professor in professors[i]:
        file_name = professor.name + "_reviews.csv"
        if os.path.exists(file_name):
            zf.write(file_name)

from IPython.display import FileLink
FileLink("professor_reviews.zip")

files.download("professor_reviews.zip")